### ISSUE TITLE
Story: Content promotion

### ISSUE THREAD

**Issue by chouseknecht** [ansible/galaxy_ng#20]
### Problem Statement
We want to track the state of a collection version with pulp repos rather than added flags (like certification flag). This also allows for defining workflow via pulp repos and promoting content across those repos.

### Automation Hub Publish Workflow
- Partner publishes to a repository specific endpoint. Publishing to `/artifacts/collections` is no longer supported.
- The repository specific URL proxies directly to a Pulp distribution endpoint.
- Pulp places the artifact into the appropriate repository for the namespace (i.e., each namespace has its own repository)
- The import process promotes the content to an 'unreviewed’ repository
- RH Partner Engineers review content in the 'unreviewed’ repository and promote accepted artifacts to either a 'certified’ or 'rejected' repository. When an artifact is promoted, it is copied to the target repository and removed from the source repository. For example, when an artifact is rejected, it gets copied to the 'rejected' repository and removed from the 'unreviewed' repository.

### Implementation Details
 - Every namespace will have a corresponding repository and distribution.
- Published artifacts are promoted to an ‘unreviewed’ repo by the import process.
- The certification page will aggregate artifacts from ‘unreviewed’ and 'rejected' repositories. Through interaction with the page, RH partner engineers can promote content to the 'certified' repository.
- All repositories are exposed via a URL endpoint.
- When RBAC is implemented, access will be controlled at the repository level such that only namespaces owners, admins and partner engineers can publish content to a namespace repository, and only admins and partner engineers can promote to the ‘unreviewed’, 'rejected' and ‘certified’ repositories. 
- The existing /artifacts/collections endpoint will no longer support a publish operation

### Subtasks
- [x] API: Content promotion move endpoint #41
- [x] API: Add per-repo _ui viewset for certification dashboard #118
- [x] Importer: Custom galaxy_ng code on import, promotion to staging #117
- [x] Infra: Expose namespace distribution URLs #40
- [x] API: Manage namespace repositories #37
- [x] API: Create repositories for existing namespaces #38
- [x] Tasking: Auto-certify with pulp repos #316
- [x] UI: Certification dashboard edits for content promotion #119
- [x] API: Update _ui collection endpoint to filter by repository #297
- [x] Disable publish to golden repo and stop using certification flag #120
- [x] Infra: Create content repositories #39

**Comment by awcrosby** [comment]
Closing as all the subtasks are now closed.
