### ISSUE TITLE
Create build repo for hub/galaxy

### ISSUE THREAD

**Issue by newswangerd** [ansible/galaxy_ng#466]
subtask of #196

In order to provide branding for the upstream versions of galaxy_ng we need to move our build process out of the `ansible-hub-ui` and `galaxy_ng` repos so that we can include the correct Red Had product branding as part of the build pipeline.

### Tasks
- [x] create  private automation hub build repo
- [x] create travis jobs for pulling the api and ui code, building it and pushing it to PyPI
- [x] create travis jobs for pulling the api and ui code, applying the downstream branding building the python packages and pushing them to some internal (to be decided) red hat repo where it can be used to build RPMs.

**Comment by newswangerd** [comment]
Moved to issues.redhat.com/
