### ISSUE TITLE
Story: Cloud environments working with 4.2.0 features

### ISSUE THREAD

**Issue by awcrosby** [ansible/galaxy_ng#489]
Items to test / work so that recent 4.2.0 on-prem related features (i.e. synclist, content promotion, rbac) work with the cloud environments.
- [x] Ensure cloud envs are providing needed bits to support docs_blob syncing via #441
- [x] Bug: Repositories created by inbound namespace migration are missing associated data #493
- [x] Test Certify and Reject UI buttons work on content in `staging`, `rejected`, and `published` as applicable
- [ ] Move content to “staging” and “rejected” repos based on certification flag #485
- [ ] Performance issue on `v3/` collection list: 504 timeout on [golden repo](https://ci.cloud.redhat.com/api/automation-hub/content/published/v3/collections/), repos with smaller number of collections do not timeout, likely related to https://pulp.plan.io/issues/7564
- [ ] Bug: Cloud user has multiple synclists in /repositories #492
- [ ] Ensure permissions have applied as needed on cloud environments, i.e. ansible-insights user has expected access
- [ ] Test publish to `inbound-<namespace>` repos is functional, and a publish to `published` is prevented
- [ ] Test installing from `published` is functional
- [ ] Ensure cloud-created synclist surfaces endpoint that works when put into on-prem
- [ ] Sync content from org repo down to local AH, may need to set pulp TLS to false: https://github.com/pulp/pulp_ansible/blob/master/pulp_ansible/tests/functional/cli/test_collection_install.py#L104-L116
- [ ] Add distribution to synclist data model #424

After testing in CI, test in QA and Stage

**Comment by newswangerd** [comment]
Moved to issues.redhat.com/
